### ISSUE TITLE
GGMarginLayout bug

### ISSUE THREAD

**Issue by walker2011** [brombres/Godot-GameGUI#1]
I think it should be like this:
### GGMarginLayout.gd line: 213
~`var y2 = rect.position.x + (rect.size.y - get_parameter(bottom_parameter,0))`~
`var y2 = rect.position.y + (rect.size.y - get_parameter(bottom_parameter,0))`

### GGMarginLayout.gd line: 38
~`right_margin = int( right_margin * ref_size.y )`~
`right_margin = int( right_margin * ref_size.x )`

**Comment by brombres** [comment]
Good catch. I've fixed this in v1.3.1:

https://github.com/brombres/Godot-GameGUI/releases

Thank you!
